{% set name = "radical.pilot" %}
{% set version = "1.62.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radical_pilot-{{ version }}.tar.gz
  sha256: bc862704912c02958c75490411afc177eb06dd4ba050433e15daa1df30bcdb58

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - radical.utils >=1.60
    - radical.gtod >=1.60
    - psij-python
    - setproctitle
    - dill

test:
  imports:
    - radical.pilot

about:
  home: https://github.com/radical-cybertools/radical.pilot
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-Pilot is a pilot-based runtime system
  description: |
    RADICAL-Pilot (RP) is a flexible pilot-based system that provides a simple
    and scalable approach for executing many concurrent simulations and their
    data requirements on high performance computing (HPC) platforms. RP
    separates resource acquisition from using those resources to execute
    application tasks.
  dev_url: https://github.com/radical-cybertools/radical.pilot

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
    - xylar
