{% set name = "radical.pilot" %}
{% set version = "1.81.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radical_pilot-{{ version }}.tar.gz
  sha256: 0738f2d0367243191ab2d5d5c15d5b19041979ad2b36143666a8650a18f5c570

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - setuptools
    - pip
  run:
    - python >=3.8
    - radical.utils >=1.80.0,<1.90
    - radical.gtod >=1.80.0,<1.90
    - psij-python
    - setproctitle
    - dill

test:
  imports:
    - radical.pilot

about:
  home: https://github.com/radical-cybertools/radical.pilot
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-Pilot is a pilot-based runtime system
  description: |
    RADICAL-Pilot (RP) is a flexible pilot-based system that provides a simple
    and scalable approach for executing many concurrent simulations and their
    data requirements on high performance computing (HPC) platforms. RP
    separates resource acquisition from using those resources to execute
    application tasks.
  dev_url: https://github.com/radical-cybertools/radical.pilot

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
    - xylar
