{% set name = "radical.pilot" %}
{% set version = "1.42.0" %}
{% set sha256 = "ed03f0174dd18b7f761cba526bbd4e07e051ea02d56b650dacf505bc1f0c74ca" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  skip: true  # [py2k or win]

requirements:
  host:
    - python
    - pip
  run:
    - python
    - radical.utils >=1.43
    - radical.saga >=1.37
    - radical.gtod
    - setproctitle
    - dill

test:
  imports:
    - radical.pilot

about:
  home: https://github.com/radical-cybertools/radical.pilot
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-Pilot is a pilot-based runtime system
  description: |
    RADICAL-Pilot (RP) is a flexible pilot-based system that provides a simple 
    and scalable approach for executing many concurrent simulations and their 
    data requirements on high performance computing (HPC) platforms. RP 
    separates resource acquisition from using those resources to execute 
    application tasks.
  dev_url: https://github.com/radical-cybertools/radical.pilot

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
