{% set name = "radical.pilot" %}
{% set version = "1.52.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/radical_pilot-{{ version }}.tar.gz
  sha256: ad477f68032e8a52b7c78bfa69557ebb8aba3ed69347590ae77620fe59114052

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  noarch: python

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - radical.utils >=1.44
    - radical.gtod
    - psij-python
    - setproctitle
    - dill

test:
  imports:
    - radical.pilot

about:
  home: https://github.com/radical-cybertools/radical.pilot
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: RADICAL-Pilot is a pilot-based runtime system
  description: |
    RADICAL-Pilot (RP) is a flexible pilot-based system that provides a simple
    and scalable approach for executing many concurrent simulations and their
    data requirements on high performance computing (HPC) platforms. RP
    separates resource acquisition from using those resources to execute
    application tasks.
  dev_url: https://github.com/radical-cybertools/radical.pilot

extra:
  recipe-maintainers:
    - andre-merzky
    - mtitov
    - xylar
