travis:
  secure:
    BINSTAR_TOKEN: ojIY3VXpnMMMftM2p+0/TJwHqYpEoKhxisMHSL5+Jxg4wQyf9K8YZ52Z/M31zqxjte/PznbCf1S3LhUR3AsMltUHrNIHXE4uq+7KH4kWtBzuse6GOl5oPBCrjYIr088ozy4JxngQL3cH5eBpqxCar9ZaqV6KyppmTXYwUYgvEwKrWTsqGBzTmkn25SdXktPMKcjlerYVUZXkzfMYsPJ+I20QsSvcN/l9LGRIfikKPRF8iKYKAjVvWMtPaSFudXfgaTSOL6A8aWE+3t/i9eq8s/lmbzhwrGEd5tEiZNBLAtUTVEAGDyVirzlFQJfjdZefvUJviDuXgdWGVa0kXJdnIwi8Z23Q2yYyctS+nvg1iDVQ14L44iSPhbEixjjTXoNWV3elEWDs+T/93Zjg+aRcTGtrGIvanEw0hENiC7iYFmPKsZzurUUKaKRvWEwXR9Z4vji/Ub7X8ll8tOC9Q6vNfqD2D/0CJSxxkMpaci3y1ypeVvc5eUcKhLka/UEpvZVspC3XvAHhAVlRoMNeIZkwHQ5y4pRDtP7mkJJHzljILL8twu79wXqI3TExnIpWG6M6FWDZ3ypiBj7BD9++5HxOM+29ognr8pY4JD3ROpVgvHJ7E125ImrL7WfeF/6ixJQkB6XF/gfHWzD9KVutbE/XAKkXumgMDFrEf3M4Vi5ALQ4=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
