travis:
  secure:
    BINSTAR_TOKEN: EXTzbLtWFMxus+sMRS75ZWnfKTcS8iD51p9ABp9Pi+xPX7kYGoP22wUzMbLflrwTvIG6HiISSy6TR3BNBDLczwdEdgNjAu7aoesvIu9VN84UFENe2adqDHNeKhIXq1eYVhuGGHM1fJtB/3iYg26Nh/xOyIn1kwCwDLo0lCjYDJ5Kyp+fjkCvBM8gnvuc5+V/W6ITrnIScR3FdT/Kkf06WuMCWR3eZilHsuwCBb/+/PWYT3Cc6pZbWeHVmxUsEABZ2PfeXJp7j3xhCYT7znCsoZrh+/NH4ciapZxU4+ZnU7o00nM5mWk4OIE3MY7lPMwOlpfd+ELmCpa1wV+9eCJyChjNdWcVO/hrOju2n2alncmsiPMB7raZ9LCl8Lkmeu2Ikjy7A/jnxBe4p+D9oKe4MilsURMqYdNjebNwuzMi93Sj/IEMnzWvA3YGUTa8mFSM8OyNHnJ+Sj+cuAEOtcSsHLbyT8FKnxVyYtzXyp5vSwRF/RZz95pHM/EEF8nhq6UYw9PN67vdhuESdloFgu5GehPLihkwbDd0FPgdWzpA5J4Jhl4j1mO0xByfAcgldDKoMXJgMfvSAoo+BDimLdIDkWO6vna9KCsAUdaA23xKtnf5fX1RMt5gT9jsU/zc7fsNd7QzcEY6f7xrK3APcpLKqPzaScgr/tGW/tKWCKZnoi4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
